# Generated by Django 3.2.19 on 2025-05-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0008_auto_20170201_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawioAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_data', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drawio_meta', to='attachments.attachment')),
            ],
            options={
                'db_table': 'drawio_attachment',
            },
        ),
    ]
